producers:
  - type: kafka_handler
    name: kafka-handler-hulk
    max_retries: 5
    brokers:
      - kafka:9092
    seceurity_protocol: PLAINTEXT
    ssl_cafile: /path/to/ca.pem
    ssl_certfile: /path/to/service.cert
    ssl_keyfile: /path/to/service.key
    ssl_password: your_ssl_password
    topic: oracle_topic
    acks: all
    batch_size: 16384
    linger_ms: 5
    buffer_memory: 33554432