services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /kafka/kraft-combined-logs
    volumes:
      - ./kafka-data:/kafka/kraft-combined-logs
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle
    environment:
      ORACLE_PASSWORD: oracle
      ORACLE_ALLOW_REMOTE: "true"
    ports:
      - "1521:1521"

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: apps_logging_app
    depends_on:
      - kafka
      - oracle
    volumes:
      - ../apps_logging_app:/app/apps_logging_app
    working_dir: /app/apps_logging_app
    command: ["python", "main.py"]

